name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug"]
type: "bug"
projects: ["octo-org/1", "octo-org/44"]
assignees:
  - octocat

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: dropdown
    id: reproducible
    attributes:
      label: Is the issue reproducible?
      description: Can you reproduce the issue consistently?
      multiple: false
      options:
        - Yes
        - No
      default: 0   # 0 = Yes, 1 = No

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce (if reproducible)
      description: >
        Please describe the exact steps to reproduce the issue.
        If it’s not reproducible, you can leave this blank.
      placeholder: |
        1. Whisper sweet nothings to your keyboard.
        2. Stare intently at the screen for 7 seconds.
        3. Click the big red button as if your pizza depends on it.
        4. Watch in awe as the app decides to throw a tantrum.
        5. Consider adopting a carrier pigeon instead of reporting bugs.
    validations:
      required: false

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Tell us what happened.
      placeholder: Describe the issue.
      value: "A bug happened!"
    validations:
      required: true

  - type: textarea
    id: expectations
    attributes:
      label: What did you expect to happen?
      description: Tell us what you would expect to happen.
      placeholder: Describe the expected behavior.
      value: "Something else should've happened!"
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: |
        Please copy and paste any relevant log output.
        This will be automatically formatted into code, so no need for backticks.
      render: shell
